version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      # Install uv for Python package management
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - export PATH="$HOME/.cargo/bin:$PATH"
      # Install all dependencies (including dev dependencies for testing)
      - uv sync
  pre_build:
    commands:
      # Activate virtual environment and run unit tests
      - source .venv/bin/activate
      - python -m pytest tests/ -v
      # Remove test files to reduce package size
      - rm -rf ./tests
      # Clean up dev dependencies (uv will handle this automatically in production install)
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yaml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
