#!/usr/bin/env ts-node
/**
 * Script to retrieve the API Key value after CDK deployment.
 * This script helps get the actual API Key value (not just the ID) for frontend configuration.
 */

import * as AWS from 'aws-sdk';
import { CloudFormation, APIGateway } from 'aws-sdk';

interface StackOutput {
  [key: string]: string;
}

class ApiKeyRetriever {
  private cloudformation: CloudFormation;
  private apigateway: APIGateway;

  constructor(region: string = 'eu-west-3') {
    AWS.config.update({ region });
    this.cloudformation = new AWS.CloudFormation();
    this.apigateway = new AWS.APIGateway();
  }

  /**
   * Retrieve the API Key value using the API Key ID.
   */
  async getApiKeyValue(apiKeyId: string): Promise<string> {
    try {
      const response = await this.apigateway.getApiKey({
        apiKey: apiKeyId,
        includeValue: true,
      }).promise();

      return response.value || '';
    } catch (error) {
      throw new Error(`Error retrieving API Key: ${error}`);
    }
  }

  /**
   * Get CloudFormation stack outputs.
   */
  async getStackOutputs(stackName: string): Promise<StackOutput> {
    try {
      const response = await this.cloudformation.describeStacks({
        StackName: stackName,
      }).promise();

      const outputs: StackOutput = {};
      const stack = response.Stacks?.[0];
      
      if (stack?.Outputs) {
        for (const output of stack.Outputs) {
          if (output.OutputKey && output.OutputValue) {
            outputs[output.OutputKey] = output.OutputValue;
          }
        }
      }

      return outputs;
    } catch (error) {
      throw new Error(`Error retrieving stack outputs: ${error}`);
    }
  }

  /**
   * Main execution function
   */
  async execute(stackName: string): Promise<void> {
    try {
      console.log(`🚀 Retrieving API configuration from stack: ${stackName}`);

      // Get stack outputs
      const outputs = await this.getStackOutputs(stackName);

      if (Object.keys(outputs).length === 0) {
        throw new Error('Failed to retrieve stack outputs');
      }

      // Get API Key ID from outputs
      const apiKeyId = outputs['ApiKeyId'];
      if (!apiKeyId) {
        console.error('ApiKeyId not found in stack outputs');
        console.log('Available outputs:', Object.keys(outputs));
        process.exit(1);
      }

      // Get API Key value
      const apiKeyValue = await this.getApiKeyValue(apiKeyId);
      if (!apiKeyValue) {
        throw new Error('Failed to retrieve API Key value');
      }

      // Print configuration for frontend
      console.log('\n=== Frontend Configuration ===');
      console.log(`API_GATEWAY_URL=${outputs['ApiGatewayUrl'] || 'NOT_FOUND'}`);
      console.log(`API_KEY=${apiKeyValue}`);

      // Create a .env file template
      const envContent = `# Regulatory Jobs Frontend Configuration
# Generated by get-api-key.ts
VITE_API_BASE_URL=${(outputs['ApiGatewayUrl'] || 'NOT_FOUND').replace(/\/$/, '')}
VITE_API_KEY=${apiKeyValue}
VITE_API_GATEWAY_ID=${outputs['ApiGatewayRestApiId'] || ''}
VITE_API_STAGE=${outputs['ApiGatewayStage'] || 'prod'}
`;

      const fs = require('fs');
      fs.writeFileSync('frontend.env', envContent);

      console.log(`\nConfiguration saved to 'frontend.env'`);
      console.log("Copy this file to your frontend directory as '.env.local'");
      console.log('\nFor automated deployment, use: npm run deploy-frontend-config');

    } catch (error) {
      console.error(`❌ Error: ${error}`);
      process.exit(1);
    }
  }
}

// Main execution
async function main() {
  const args = process.argv.slice(2);
  
  if (args.length !== 1) {
    console.log('Usage: ts-node get-api-key.ts <stack-name>');
    console.log('Example: ts-node get-api-key.ts RegulatoryJobsStack');
    process.exit(1);
  }

  const stackName = args[0];
  const retriever = new ApiKeyRetriever();
  
  await retriever.execute(stackName);
}

if (require.main === module) {
  main().catch(console.error);
}